<?php

use application\locations\Url;
use application\model\General;
use application\model\Links;

if (!isset($View_Controller)) die("View Controller not found");
?>

<!doctype html>

<html class="no-touch no-js">
<!--<![endif]-->

<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<base href="<?php Url::url() ?><!--" />
<?php $View_Controller->Load()->widget()->Load("public-head") ?>

<body id="supply-theme-demo-shop-by-shopify" class="template-index">

<?php $View_Controller->Load()->widget()->Load("public-navbar") ?>

<main class="wrapper main-content" role="main">


</main>

<?php $View_Controller->Load()->widget()->Load("public-footer") ?>
</body>

</html>
