<div class="pcoded-inner-content collection-add" app-brand>
    <div class="main-body">
        <div class="page-wrapper">
            <div class="row align-items-end mb-3">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <div class="d-inline">
                            <h4>Create Brand</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="#"> <i class="feather icon-home"></i> </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Brand</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Create Brand</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="page-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card container">
                            <div class="card-header">
                                <h5>Create</h5>
                            </div>
                            <div class="card-block">
                                <form class="" app-brand-add>
                                    <div class="row">
                                        <div class="col-lg-3 brand-image">
                                            <img src="browser/images/brands/brand.jpg" class="brand-logo img-thumbnail" app-brand-preview>
                                            <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                            <div class="img-loader" app-brand-loader>
                                                <i class="fa fa-spinner fa-spin"></i>
                                            </div>
                                        </div>
                                        <div class="col-lg-9">
                                            <div class="form-group">
                                                <input type="text" name="name" id="name" class="form-control" placeholder="Brand Name">
                                                <input type="hidden" app-brand-link name="url">
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-primary btn-round pull-right">
                                                    Create Brand
                                                </button>
                                            </div>
                                        </div>
                                    </div>



                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>