<?php

use application\locations\Url;
use application\model\General;
use application\model\Links;

if (!isset($View_Controller)) die("View Controller not found");
?>

<!doctype html>

<html class="no-touch no-js">
<!--<![endif]-->

<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<base href="<?php Url::url() ?><!--" />
<?php $View_Controller->Load()->widget()->Load("public-head") ?>

<body id="supply-theme-demo-shop-by-shopify" class="template-index">

<?php $View_Controller->Load()->widget()->Load("public-navbar") ?>

<main class="wrapper main-content" role="main">


<nav class="breadcrumb" role="navigation" aria-label="breadcrumbs">
    <a href="index" title="Back to the frontpage">Home</a>



    <span class="divider" aria-hidden="true">&rsaquo;</span>
    <span>About Us</span>


</nav>



<div class="grid">

    <div class="grid-item large--two-thirds push--large--one-sixth">

        <h1>About Us</h1>

        <div class="rte">
            <meta charset="utf-8">
            <p><img src="../../cdn.shopify.com/s/files/1/0543/1637/files/KDV09802edit2_large_109dca71-0eab-4b40-af46-b2bba9f5feea_largef1b7.jpg?v=1508946196" alt=""></p>
            <p>Professionals, enthusiasts, and newcomers alike are welcome to experience our products first-hand, and our warm, knowledgeable and professional staff is here to provide expert information and friendly service and to ensure the ultimate in customer satisfaction.</p>
            <p>Our gallery showcases a rotating exhibit of images, enabling customers to get an up-close look at how Leica has become a witness to history and a tool in creating the finest photographic art. In addition, we host several in-house demos and workshops for professionals and enthusiasts seeking to discover or enhance their photographic skills.</p>
            <p>We are truly thrilled for the opportunity to share our passion for photography with the community.</p>
        </div>

    </div>

</div>

</main>

<?php $View_Controller->Load()->widget()->Load("public-footer") ?>
</body>

</html>