<div class="pcoded-inner-content">

    <div class="main-body">
        <div class="page-wrapper">

            <div class="page-header">
                <div class="row align-items-end">
                    <div class="col-lg-8">
                        <div class="page-header-title">
                            <div class="d-inline">
                                <h4>Add Product</h4>

                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="page-header-breadcrumb">
                            <ul class="breadcrumb-title">
                                <li class="breadcrumb-item">
                                    <a href="index-2.html"> <i class="feather icon-home"></i> </a>
                                </li>
                                <li class="breadcrumb-item"><a href="#!">Dashboard</a>
                                </li>
                                <li class="breadcrumb-item"><a href="#!">create Product </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="page-body">
                <div class="row">
                    <div class="col-sm-12">

                        <div class="card">
                            <div class="card-header">
                                <h5>Add Product </h5>
                            </div>
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="product-edit">
                                            <form class="md-float-material card-block">
                                                <div class="row">
                                                    <div class="col-sm-12 col-lg-5 offset-3">
                                                        <img src="browser/dash/images/brand-icon.png" class="brand-logo img-thumbnail" app-brand-preview>
                                                        <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                                        <div class="img-loader" app-brand-loader>
                                                            <i class="fa fa-spinner fa-spin"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-12 col-md-2">
                                                        <img src="browser/dash/images/brand-icon.png" class="brand-logo img-thumbnail" app-brand-preview>
                                                        <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                                        <div class="img-loader" app-brand-loader>
                                                            <i class="fa fa-spinner fa-spin"></i>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2">
                                                        <img src="browser/dash/images/brand-icon.png" class="brand-logo img-thumbnail" app-brand-preview>
                                                        <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                                        <div class="img-loader" app-brand-loader>
                                                            <i class="fa fa-spinner fa-spin"></i>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2">
                                                        <img src="browser/dash/images/brand-icon.png" class="brand-logo img-thumbnail" app-brand-preview>
                                                        <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                                        <div class="img-loader" app-brand-loader>
                                                            <i class="fa fa-spinner fa-spin"></i>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2">
                                                        <img src="browser/dash/images/brand-icon.png" class="brand-logo img-thumbnail" app-brand-preview>
                                                        <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                                        <div class="img-loader" app-brand-loader>
                                                            <i class="fa fa-spinner fa-spin"></i>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2">
                                                        <img src="browser/dash/images/brand-icon.png" class="brand-logo img-thumbnail" app-brand-preview>
                                                        <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                                        <div class="img-loader" app-brand-loader>
                                                            <i class="fa fa-spinner fa-spin"></i>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2">
                                                        <img src="browser/dash/images/brand-icon.png" class="brand-logo img-thumbnail" app-brand-preview>
                                                        <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                                        <div class="img-loader" app-brand-loader>
                                                            <i class="fa fa-spinner fa-spin"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <div class="input-group">
                                                            <span class="input-group-addon"><i
                                                                        class="fa fa-itunes-note"></i></span>
                                                            <input type="text" class="form-control"
                                                                   placeholder="Product Name">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <select name="select" class="form-control form-control-primary">
                                                            <option value="opt1">Select Brand</option>
                                                            <option value="opt2">2</option>
                                                            <option value="opt3">3</option>
                                                            <option value="opt4">4</option>
                                                            <option value="opt5">5</option>
                                                            <option value="opt6">6</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <div class="input-group">
                                                            <span class="input-group-addon"><i
                                                                        class="fa fa-money-bill"></i></span>
                                                            <input type="text" class="form-control"
                                                                   placeholder="Price">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <select name="select" class="form-control form-control-primary">
                                                            <option value="opt1">Select Model</option>
                                                            <option value="opt2">2</option>
                                                            <option value="opt3">3</option>
                                                            <option value="opt4">4</option>
                                                            <option value="opt5">5</option>
                                                            <option value="opt6">6</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <div class="input-group">
                                                            <span class="input-group-addon"><i
                                                                        class="icofont icofont-copy-alt"></i></span>
                                                            <input type="text" class="form-control"
                                                                   placeholder="Product Description">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <select name="select" class="form-control form-control-primary">
                                                            <option value="opt1">Select One Value Only</option>
                                                            <option value="opt2">2</option>
                                                            <option value="opt3">3</option>
                                                            <option value="opt4">4</option>
                                                            <option value="opt5">5</option>
                                                            <option value="opt6">6</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-12 col-md-4 offset-4">
                                                        <div class="text-center m-t-20">
                                                            <button type="button"
                                                                    class="btn btn-primary btn-block waves-effect waves-light m-r-10">
                                                                Add Product
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>