<?php
use application\locations\Url;
use application\model\General;
use application\model\Links;
if(!isset($View_Controller))die("View Controller not found");
?>
<!DOCTYPE html>
<html lang="en">

<?php $View_Controller->Load()->Widget()->Load("public-head"); ?>

<body>

<div id="layoutDefault">

    <div id="layoutDefault_content">

        <main>

            <?php $View_Controller->Load()->Widget()->Load("public-navbar"); ?>

            <header class="page-header page-header-dark bg-gradient-primary-to-secondary">
                <div class="page-header-content pt-10">
                    <div class="container text-center">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <h1 class="page-header-title mb-3">Loans Packages</h1>
                                <p class="page-header-text">These are the list of our loan packages.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="svg-border-rounded text-white">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none" fill="currentColor"><path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0" /></svg>
                </div>
            </header>

            <section class="bg-light py-10">
                <div class="container">
                    <div class="text-center mb-5">
                        <h2>Simple Pricing</h2>
                        <p class="lead">Easy pricing means no suprises.</p>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 mb-5 mb-lg-0">
                            <div class="card pricing h-100">
                                <div class="card-body p-5">
                                    <div class="text-center">
                                        <div class="badge badge-light badge-pill badge-marketing badge-sm">Free</div>
                                        <div class="pricing-price"><sup>$</sup>0<span class="pricing-price-period">/mo</span></div>
                                    </div>
                                    <ul class="fa-ul pricing-list">
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">1 user</span>
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">Community support</span>
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-circle text-gray-200"></i></span>Style customizer
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-circle text-gray-200"></i></span>Custom components
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-circle text-gray-200"></i></span>Expanded utilities
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-circle text-gray-200"></i></span>Third-party integration
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-circle text-gray-200"></i></span>Layout options
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 mb-5 mb-lg-0">
                            <div class="card pricing h-100">
                                <div class="card-body p-5">
                                    <div class="text-center">
                                        <div class="badge badge-primary-soft badge-pill badge-marketing badge-sm text-primary">Standard</div>
                                        <div class="pricing-price"><sup>$</sup>19<span class="pricing-price-period">/mo</span></div>
                                    </div>
                                    <ul class="fa-ul pricing-list">
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">Up to 15 users</span>
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">Email and live chat support</span>
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">Style customizer</span>
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">Custom components</span>
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">Expanded utilities</span>
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">Third-party integration</span>
                                        </li>
                                        <li class="pricing-list-item">
                                            <span class="fa-li"><i class="far fa-check-circle text-teal"></i></span><span class="text-dark">Layout options</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="card pricing h-100">
                                <div class="card-body p-5">
                                    <div class="text-center">
                                        <div class="badge badge-light badge-pill badge-marketing badge-sm">Enterprise</div>
                                        <p class="card-text py-10">We offer discounts for larger organizations. Contact us to inquire about enterprise level plans!</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mt-5 text-center"><a class="btn btn-primary btn-marketing rounded-pill" href="#!">Get Started</a></div>
                </div>
            </section>

        </main>

    </div>

    <?php $View_Controller->Load()->Widget()->Load("public-footer"); ?>

</div>

<?php $View_Controller->Load()->Widget()->Load("public-footer-script"); ?>

</body>
</html>

