<div class="pcoded-inner-content" app-password>
    <div class="main-body">
        <div class="page-wrapper">
            <div class="row align-items-end mb-3">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <div class="d-inline">
                            <h4>Password Reset</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="#"> <i class="feather icon-home"></i> </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Reset Password</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Reset Password</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="page-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card container-fluid">
                            <div class="card-header">
                                <h5>Admin Password Settings</h5>
                            </div>
                            <div class="card-block col-sm-12 col-xl-5 m-b-10 m-t-10 offset-4">
                                <form method="post" app-password-reset>
                                    <div class="form-group">
                                        <input type="password" class="form-control has-error" name="oldPassword" placeholder="Old Password"/>
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control has-error" name="newPassword" placeholder="new Password"/>
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control has-error" name="repeatPassword" placeholder="Repeat Password"/>
                                    </div>
                                    <button class="btn btn-primary btn-round" type="submit">Reset Password</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>