<?php

use application\database\Database;
use model\Brand;

$db = new Database();
$Brand = new Brand($db);
$List = $Brand->Listing();
?>
<div class="pcoded-inner-content" app-model>
    <div class="main-body">
        <div class="page-wrapper">
            <div class="row align-items-end mb-3">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <div class="d-inline">
                            <h4>Create Model</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="#"> <i class="feather icon-home"></i> </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Model</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Create Models</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="page-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="col-sm-12 col-xl-5 m-b-10 m-t-10 offset-4">
                                <form method="post" app-model-add>
                                    <div class="form-group">
                                        <label class="form-label">Select Brand</label>
                                        <select name="brand" class="form-control form-control-info">
                                            <option value="">Select Brand name</option>
                                            <?php
                                            foreach ($List as $item){
                                                $id = $item->id;
                                                $name = $item->name;
                                                echo "<option value='$id'>$name</option>";
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" name="name" placeholder="Model Name"/>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Create</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>