<?php

use application\locations\Url;
use application\model\General;
use application\model\Links;

if (!isset($View_Controller)) die("View Controller not found");
?>

<!DOCTYPE html>
<html lang="en">

    <?php $View_Controller->Load()->Widget()->Load("admin-head") ?>

    <body class="fix-menu">

        <div class="theme-loader">
            <div class="ball-scale">
                <div class='contain'>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                    <div class="ring"><div class="frame"></div></div>
                </div>
            </div>
        </div>

        <section class="login-block">

            <div class="container">
                <div class="row">
                    <div class="col-sm-12">

                        <form class="md-float-material form-material for" admin-login>
                            <div class="text-center">
                                <img  style="width: 180px" src="browser/logo.png" alt="logo.png">
                            </div>
                            <div class="auth-box card">
                                <div class="card-block">
                                    <div class="row m-b-20">
                                        <div class="col-md-12">
                                            <h3 class="text-center">Sign In</h3>
                                        </div>
                                    </div>
                                    <div class="form-group form-primary">
                                        <input type="text" name="email" class="form-control" required="" placeholder="Your Email Address">
                                        <span class="form-bar"></span>
                                    </div>
                                    <div class="form-group form-primary">
                                        <input type="password" name="password" class="form-control" required="" placeholder="Password">
                                        <span class="form-bar"></span>
                                    </div>
                                    <div class="row m-t-30">
                                        <div class="col-md-12">
                                            <button type="submit" class="btn btn-primary btn-md btn-block waves-effect waves-light text-center m-b-20">Sign in</button>
                                        </div>
                                    </div>
                                    <hr/>
                                </div>
                            </div>
                        </form>

                    </div>

                </div>

            </div>

        </section>

        <?php $View_Controller->Load()->Widget()->Load("admin-footer") ?>

    </body>
</html>
