<?php

use application\locations\Url;
use application\model\General;
use application\model\Links;

if (!isset($View_Controller)) die("View Controller not found");
?>

<!doctype html>

<html class="no-touch no-js">
<!--<![endif]-->

<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<base href="<?php Url::url() ?><!--" />
<?php $View_Controller->Load()->widget()->Load("public-head") ?>

<body id="supply-theme-demo-shop-by-shopify" class="template-index">

<?php $View_Controller->Load()->widget()->Load("public-navbar") ?>

<main class="wrapper main-content" role="main">

    <div id="EmptyCart">
        <h1 class="h2">Shopping Cart</h1>
        <p class="cart--empty-message">Your cart is currently empty.</p>
        <p class="cart--continue-message">Continue browsing <a href="collectionList">here</a>.</p>
        <p class="cart--cookie-message">Enable cookies to use the shopping cart</p>
    </div>


</main>

<?php $View_Controller->Load()->widget()->Load("public-footer") ?>
</body>

</html>
