<?php

use application\database\Database;
use application\locations\Url;
use model\Brand;

$db = new Database();
$Brand = new Brand($db);
$List = $Brand->Listing();
?>
<div class="pcoded-inner-content brand-list collection-add" app-brand>
    <div class="main-body">
        <div class="page-wrapper">
            <div class="row align-items-end mb-3">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <div class="d-inline">
                            <h4>Brand Manage</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="#"> <i class="feather icon-home"></i> </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Brand</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Manage Brand</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="page-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Brand List</h5>
                            </div>
                            <div class="card-block table-border-style">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Brand logo</th>
                                            <th>Brand Name</th>
                                            <th>Total Models</th>
                                            <th>Created</th>
                                            <th>Last Updated</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($List as $item){
                                            $id = $item->id;
                                            $name = $item->name;
                                            $totalModels = $item->totalModels;
                                            $filename = Url::Url_upload($item->image);
                                            $created = date("Y-m-d (h:iA)",floatval($item->created));
                                            $updated = (is_null($item->updated))?
                                                "Not Updated Yet":
                                                date("Y-m-d (h:iA)",floatval($item->updated));
                                            ?>
                                            <tr app-brand-item="<?=$id?>">
                                                <th><?=$id?></th>
                                                <td>
                                                    <img class="brand-logo" app-update-filename src="<?=$filename?>" alt="Brand">
                                                </td>
                                                <td app-update-name><?=$name?></td>
                                                <td><?=$totalModels?></td>
                                                <td><?=$created?></td>
                                                <td app-update-update><?=$updated?></td>
                                                <td class="right">
                                                    <button app-edit class="btn btn-sm btn-info" data-toggle="modal" data-target="#edit-brand">
                                                        <span class="fa fa-edit"></span>
                                                    </button>
                                                    <button app-delete class="btn btn-sm btn-danger">
                                                        <span class="fa fa-remove"></span>
                                                    </button>
                                                </td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-------MODAL BEGIN HERE--->
                            <div app-edit-box class="modal fade" role="dialog" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="login-card card-block modal-body">
                                        <div class="md-float-material">
                                            <div class="card m-t-15">
                                                <div class="auth-box card-block">
                                                    <div class="row m-b-20">
                                                        <div class="col-md-12">
                                                            <h4 class="text-left txt-primary">Edit Brand</h4>
                                                        </div>
                                                    </div>
                                                    <div class="card-block">
                                                        <form app-brand-update>
                                                            <div class="row">
                                                                <div class="col-lg-5 brand-image">
                                                                    <img src="browser/dash/images/brand-icon.png" class="brand-logo img-thumbnail" app-brand-preview>
                                                                    <input type="file" accept="image/jpg,image/jpeg,image/png" class="brand-file" app-brand-file>
                                                                    <div class="img-loader" app-brand-loader>
                                                                        <i class="fa fa-spinner fa-spin"></i>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-7">
                                                                    <div class="form-group">
                                                                        <input type="text" name="name" class="form-control" placeholder="Brand Name">
                                                                        <input type="hidden" app-brand-link name="url">
                                                                        <input type="hidden" app-brand-id name="id">
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <button type="submit" class="btn btn-primary btn-round pull-right">
                                                                            Update Brand
                                                                        </button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <!-------MODAL ENDS HERE--->
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>