<div class="pcoded-inner-content news" app-news>
    <div class="main-body">
        <div class="page-wrapper">
            <div class="row align-items-end mb-3">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <div class="d-inline">
                            <h4>Create Jobs/News Post</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="#"> <i class="feather icon-home"></i> </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Jobs/News Post</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">Create Jobs/News Post</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="page-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-block">
                                <form app-jobs-add>
                                    <div class="form-group">
                                        <input class="form-control form-control-info" name="title" type="text" placeholder="Tilte"/>
                                    </div>
                                    <div class="form-group">
                                        <textarea job-body name="body" class="form-control" rows="10" cols="80"  id="editor1" ></textarea>
                                    </div>
                                    <div class="form-group">
                                        <button app-post-btn type="button" class="btn btn-primary">Post News</button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
