<?php


namespace model;


class Links{

    const adm_dashboard = "admin_dashboard";
    const adm_order = "admin_order";
    const adm_customer_list = "admin_customer_list";
    const adm_product_add = "admin_product_add";
    const adm_product_list = "admin_product_list";
    const adm_brand_add = "admin_brand_add";
    const adm_brand_list = "admin_brand_list";
    const adm_model_add = "admin_model_add";
    const adm_model_list = "admin_model_list";
    const adm_staff_add = "admin_staff-add";
    const adm_staff_list = "admin_staff_list";
    const adm_password = "admin_password";

}