<?php
use model\Links;
?>
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu" app-navigation>
        <div class="pcoded-navigatio-lavel">Navigation</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="active pcoded-trigger">
                <a href="#" app-link="<?=Links::adm_dashboard?>">
                    <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                    <span class="pcoded-mtext">Dashboard</span>
                </a>
            </li>
            <li class="">
                <a href="#" app-link="<?=Links::adm_order?>">
                    <span class="pcoded-micon"><i class="feather icon-menu"></i></span>
                    <span class="pcoded-mtext">Orders</span>
                </a>
            </li>
            <li class="">
                <a href="#" app-link="<?=Links::adm_customer_list?>">
                    <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                    <span class="pcoded-mtext">Customers</span>

                </a>
            </li>
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-layers"></i></span>
                    <span class="pcoded-mtext">Products</span>

                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_product_add?>">
                            <span class="pcoded-mtext">Add product</span>
                        </a>
                    </li>

                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_product_list?>">
                            <span class="pcoded-mtext">Lists Products</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="">
                <a href="#">
                    <span class="pcoded-micon"><i class="feather icon-check"></i></span>
                    <span class="pcoded-mtext">Stock Products</span>
                </a>
            </li>
            <li class="">
                <a href="#" app-link="<?=""?>">
                    <span class="pcoded-micon"><i class="feather icon-layers"></i></span>
                    <span class="pcoded-mtext">Tickets</span>

                </a>

            </li>
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-layers"></i></span>
                    <span class="pcoded-mtext">Staff</span>

                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="#">
                            <span class="pcoded-mtext">Add Staff</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#">
                            <span class="pcoded-mtext">List Staffs</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-settings"></i></span>
                    <span class="pcoded-mtext">Settings</span>

                </a>
                <ul class="pcoded-submenu">
                    <li class="">
                        <a href="#" app-link="<?=Links::adm_brand_add?>">
                            <span class="pcoded-mtext">Add Brand</span>
                        </a>
                    </li>

                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_brand_list?>">
                            <span class="pcoded-mtext">Manage Brand</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_model_add?>">
                            <span class="pcoded-mtext">Add Models</span>
                        </a>
                    </li>

                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_model_list?>">
                            <span class="pcoded-mtext">Manage Models</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_password?>">
                            <span class="pcoded-mtext">Passwords</span>
                        </a>
                    </li>

                    <li class=" ">
                        <a href="#" target="_blank">
                            <span class="pcoded-mtext">Reviews</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <div class="pcoded-navigatio-lavel">News Feed</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-box"></i></span>
                    <span class="pcoded-mtext">News</span>
                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="#">
                            <span class="pcoded-mtext">Add News</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#">
                            <span class="pcoded-mtext">News List</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-package"></i></span>
                    <span class="pcoded-mtext">Notifications</span>
                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="#">
                            <span class="pcoded-mtext">Notifi</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#l">
                            <span class="pcoded-mtext">Assign Notification</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#">
                            <span class="pcoded-mtext">Post Notification</span>
                        </a>
                    </li>
                </ul>
            </li>

        </ul>
        <div class="pcoded-navigatio-lavel">Reveun/Payment</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="pcoded-hasmenu">
                <a href="#">
                    <span class="pcoded-micon"><i class="feather icon-clipboard"></i></span>
                    <span class="pcoded-mtext">Reveun</span>
                </a>
            </li>
            <li class="pcoded-hasmenu">
                <a href="#">
                    <span class="pcoded-micon"><i class="feather icon-edit-1"></i></span>
                    <span class="pcoded-mtext">Payment</span>
                </a>
            </li>

        </ul>
    </div>
</nav>