<head>
    <!-- Basic page needs ================================================== -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- Title and description ================================================== -->
    <title>
        Ecommerce Shopping
    </title>



    <!-- Product meta ================================================== -->
    <meta property="og:site_name" content="">
    <meta property="og:url" content="">
    <meta property="og:title" content="">
    <meta property="og:type" content="website">
    <meta property="og:description" content="">



    <!-- Helpers ================================================== -->
    <link rel="canonical" href="">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- CSS ================================================== -->
    <link href="browser/customer/files/1/0543/1637/t/16/assets/theme.scss621d.css" rel="stylesheet" type="text/css" media="all" />
    <link href="browser/customer/fontawesome/css/all.css" rel="stylesheet">

    <!-- Header hook for plugins ================================================== -->
    <script>
        window.performance && window.performance.mark && window.performance.mark('shopify.content_for_header.start');
    </script>

    <script type="module">!function(o){(o.Shopify=o.Shopify||{}).modules=!0}(window);</script>
    <script>
        ! function(o) {
            function n() {
                var o = [];

                function n() {
                    o.push(Array.prototype.slice.apply(arguments))
                }
                return n.q = o, n
            }
            var t = o.Shopify = o.Shopify || {};
            t.loadFeatures = n(), t.autoloadFeatures = n()
        }(window);
    </script>

    <script class="analytics">
        (function() {
            var customDocumentWrite = function(content) {
                var jquery = null;

                if (window.jQuery) {
                    jquery = window.jQuery;
                } else if (window.Checkout && window.Checkout.$) {
                    jquery = window.Checkout.$;
                }

                if (jquery) {
                    jquery('body').append(content);
                }
            };

            var isDuplicatedThankYouPageView = function() {
                return document.cookie.indexOf('loggedConversion=' + window.location.pathname) !== -1;
            }

            var setCookieIfThankYouPage = function() {
                if (window.location.pathname.indexOf('/checkouts') !== -1 &&
                    window.location.pathname.indexOf('/thank_you') !== -1) {

                    var twoMonthsFromNow = new Date(Date.now());
                    twoMonthsFromNow.setMonth(twoMonthsFromNow.getMonth() + 2);

                    document.cookie = 'loggedConversion=' + window.location.pathname + '; expires=' + twoMonthsFromNow;
                }
            }

            var trekkie = window.ShopifyAnalytics.lib = window.trekkie = window.trekkie || [];
            if (trekkie.integrations) {
                return;
            }
            trekkie.methods = [
                'identify',
                'page',
                'ready',
                'track',
                'trackForm',
                'trackLink'
            ];
            trekkie.factory = function(method) {
                return function() {
                    var args = Array.prototype.slice.call(arguments);
                    args.unshift(method);
                    trekkie.push(args);
                    return trekkie;
                };
            };
            for (var i = 0; i < trekkie.methods.length; i++) {
                var key = trekkie.methods[i];
                trekkie[key] = trekkie.factory(key);
            }
            trekkie.load = function(config) {
                trekkie.config = config;
                var script = document.createElement('script');
                script.type = 'text/javascript';
                script.onerror = function(e) {
                    (new Image()).src = '';
                };
                script.async = true;
                script.src = 'browser/customer/javascripts/tricorder/trekkie.storefront.min7bee.js';
                var first = document.getElementsByTagName('script')[0];
                first.parentNode.insertBefore(script, first);
            };
            trekkie.load({
                "Trekkie": {
                    "appName": "storefront",
                    "development": false,
                    "defaultAttributes": {
                        "shopId": 5431637,
                        "isMerchantRequest": null,
                        "themeId": 37530075192,
                        "themeCityHash": "1361009156021012140",
                        "contentLanguage": "en",
                        "currency": "CAD"
                    },
                    "isServerSideCookieWritingEnabled": true
                },
                "Performance": {
                    "navigationTimingApiMeasurementsEnabled": true,
                    "navigationTimingApiMeasurementsSampleRate": 1
                },
                "Session Attribution": {}
            });

            var loaded = false;
            trekkie.ready(function() {
                if (loaded) return;
                loaded = true;

                window.ShopifyAnalytics.lib = window.trekkie;


                var originalDocumentWrite = document.write;
                document.write = customDocumentWrite;
                try {
                    window.ShopifyAnalytics.merchantGoogleAnalytics.call(this);
                } catch (error) {};
                document.write = originalDocumentWrite;
                (function() {
                    if (window.BOOMR && (window.BOOMR.version || window.BOOMR.snippetExecuted)) {
                        return;
                    }
                    window.BOOMR = window.BOOMR || {};
                    window.BOOMR.snippetStart = new Date().getTime();
                    window.BOOMR.snippetExecuted = true;
                    window.BOOMR.snippetVersion = 12;
                    window.BOOMR.application = "core";
                    window.BOOMR.shopId = 5431637;
                    window.BOOMR.themeId = 37530075192;
                    window.BOOMR.url =
                        "browser/customer/boomerang/shopify-boomerang-1.0.0.min.js";
                    var where = document.currentScript || document.getElementsByTagName("script")[0];
                    var parentNode = where.parentNode;
                    var promoted = false;
                    var LOADER_TIMEOUT = 3000;

                    function promote() {
                        if (promoted) {
                            return;
                        }
                        var script = document.createElement("script");
                        script.id = "boomr-scr-as";
                        script.src = window.BOOMR.url;
                        script.async = true;
                        parentNode.appendChild(script);
                        promoted = true;
                    }

                    function iframeLoader(wasFallback) {
                        promoted = true;
                        var dom, bootstrap, iframe, iframeStyle;
                        var doc = document;
                        var win = window;
                        window.BOOMR.snippetMethod = wasFallback ? "if" : "i";
                        bootstrap = function(parent, scriptId) {
                            var script = doc.createElement("script");
                            script.id = scriptId || "boomr-if-as";
                            script.src = window.BOOMR.url;
                            BOOMR_lstart = new Date().getTime();
                            parent = parent || doc.body;
                            parent.appendChild(script);
                        };
                        if (!window.addEventListener && window.attachEvent && navigator.userAgent.match(/MSIE [67]./)) {
                            window.BOOMR.snippetMethod = "s";
                            bootstrap(parentNode, "boomr-async");
                            return;
                        }
                        iframe = document.createElement("IFRAME");
                        iframe.src = "about:blank";
                        iframe.title = "";
                        iframe.role = "presentation";
                        iframe.loading = "eager";
                        iframeStyle = (iframe.frameElement || iframe).style;
                        iframeStyle.width = 0;
                        iframeStyle.height = 0;
                        iframeStyle.border = 0;
                        iframeStyle.display = "none";
                        parentNode.appendChild(iframe);
                        try {
                            win = iframe.contentWindow;
                            doc = win.document.open();
                        } catch (e) {
                            dom = document.domain;
                            iframe.src = "javascript:var d=document.open();d.domain='" + dom + "';void(0);";
                            win = iframe.contentWindow;
                            doc = win.document.open();
                        }
                        if (dom) {
                            doc._boomrl = function() {
                                this.domain = dom;
                                bootstrap();
                            };
                            doc.write("<body onload='document._boomrl();'>");
                        } else {
                            win._boomrl = function() {
                                bootstrap();
                            };
                            if (win.addEventListener) {
                                win.addEventListener("load", win._boomrl, false);
                            } else if (win.attachEvent) {
                                win.attachEvent("onload", win._boomrl);
                            }
                        }
                        doc.close();
                    }
                    var link = document.createElement("link");
                    if (link.relList &&
                        typeof link.relList.supports === "function" &&
                        link.relList.supports("preload") &&
                        ("as" in link)) {
                        window.BOOMR.snippetMethod = "p";
                        link.href = window.BOOMR.url;
                        link.rel = "preload";
                        link.as = "script";
                        link.addEventListener("load", promote);
                        link.addEventListener("error", function() {
                            iframeLoader(true);
                        });
                        setTimeout(function() {
                            if (!promoted) {
                                iframeLoader(true);
                            }
                        }, LOADER_TIMEOUT);
                        BOOMR_lstart = new Date().getTime();
                        parentNode.appendChild(link);
                    } else {
                        iframeLoader(false);
                    }

                    function boomerangSaveLoadTime(e) {
                        window.BOOMR_onload = (e && e.timeStamp) || new Date().getTime();
                    }
                    if (window.addEventListener) {
                        window.addEventListener("load", boomerangSaveLoadTime, false);
                    } else if (window.attachEvent) {
                        window.attachEvent("onload", boomerangSaveLoadTime);
                    }
                    if (document.addEventListener) {
                        document.addEventListener("onBoomerangLoaded", function(e) {
                            e.detail.BOOMR.init({
                                ResourceTiming: {
                                    enabled: true,
                                    trackedResourceTypes: ["script", "img", "css"]
                                },
                            });
                            e.detail.BOOMR.t_end = new Date().getTime();
                        });
                    } else if (document.attachEvent) {
                        document.attachEvent("onpropertychange", function(e) {
                            if (!e) e = event;
                            if (e.propertyName === "onBoomerangLoaded") {
                                e.detail.BOOMR.init({
                                    ResourceTiming: {
                                        enabled: true,
                                        trackedResourceTypes: ["script", "img", "css"]
                                    },
                                });
                                e.detail.BOOMR.t_end = new Date().getTime();
                            }
                        });
                    }
                })();


                if (!isDuplicatedThankYouPageView()) {
                    setCookieIfThankYouPage();

                    window.ShopifyAnalytics.lib.page(
                        null, {
                            "pageType": "home"
                        }
                    );


                }
            });


            var eventsListenerScript = document.createElement('script');
            eventsListenerScript.async = true;
            eventsListenerScript.src = "browser/customer/assets/shop_events_listener-2c6237918c4bbec8783d8ceecd5759edc38afa9b5bef55134462710955517539.js";
            document.getElementsByTagName('head')[0].appendChild(eventsListenerScript);

        })();
    </script>
    <script  crossorigin="anonymous"  defer="defer" src="browser/customer/assets/storefront/load_feature.js"></script>
    <script  defer="defer" src="browser/customer/assets/storefront/features.js" crossorigin="anonymous"></script>



    <script defer="defer" src="browser/customer/assets/themes_support/ga_urchin_forms.js"></script>


    <script>
        window.performance && window.performance.mark && window.performance.mark('shopify.content_for_header.end');
    </script>






    <script src="browser/customer/files/1/0543/1637/t/16/assets/jquery-2.2.3.min4dfb.js" type="text/javascript"></script>

    <script src="browser/customer/files/1/0543/1637/t/16/assets/lazysizes.minb2e8.js" async="async"></script>

    <script src="browser/customer/files/1/0543/1637/t/16/assets/vendor5ffc.js" defer="defer"></script>

    <script src="browser/customer/files/1/0543/1637/t/16/assets/theme4d8f.js" defer="defer"></script>


</head>


