<?php

use application\locations\Url; ?>
<head>
    <title>Tele-Tech Admin </title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="#">

    <base href="<?=Url::Url();?>/">

    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <link rel="apple-touch-icon" sizes="57x57" href="browser/images/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="browser/images/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="browser/images/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="browser/images/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="browser/images/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="browser/images/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="browser/images/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="browser/images/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="browser/images/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="browser/images/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="browser/images/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="browser/images/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="browser/images/icons/favicon-16x16.png">
    <link rel="manifest" href="browser/images/icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="browser/images/icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">


    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="browser/dash/vendor/bootstrap/css/bootstrap.min.css">


    <link rel="stylesheet" type="text/css" href="browser/dash/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="browser/dash/vendor/datatables.net/css/buttons.dataTables.min.css">


    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.css" type="text/css">
    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.brighttheme.css" type="text/css">
    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.buttons.css" type="text/css">
    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.history.css" type="text/css">
    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.mobile.css" type="text/css">


    <link rel="stylesheet" type="text/css" href="browser/dash/icons/feather/css/feather.css">
    <link rel="stylesheet" type="text/css" href="browser/dash/icons/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="browser/dash/css/jquery.mCustomScrollbar.css">
    <link rel="stylesheet" type="text/css" href="browser/dash/css/style.css">
    <link rel="stylesheet" type="text/css" href="browser/dash/css/custom.css">

</head>