<head>
    <script>
        (function(H) {
            H.className = H.className.replace(/\bno-js\b/, 'js')
        })(document.documentElement)
    </script>
    <!-- Basic page needs ================================================== -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">



    <!-- Title and description ================================================== -->
    <title>
        Ecommerce Shopping
    </title>



    <!-- Product meta ================================================== -->
    <!-- /snippets/social-meta-tags.liquid -->



    <meta property="og:site_name" content="">
    <meta property="og:url" content="">
    <meta property="og:title" content="">
    <meta property="og:type" content="website">
    <meta property="og:description" content="">



    <!-- Helpers ================================================== -->
    <link rel="canonical" href="">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- CSS ================================================== -->
    <link href="browser/customer/files/1/0543/1637/t/16/assets/theme.scss621d.css" rel="stylesheet" type="text/css" media="all" />
    <link href="browser/customer/fontawesome/css/all.css" rel="stylesheet">

    <!-- Header hook for plugins ================================================== -->
    <script>
        window.performance && window.performance.mark && window.performance.mark('shopify.content_for_header.start');
    </script>


    <script>
        var Shopify = Shopify || {};
        Shopify.shop = "supply-electronics.myshopify.com";
        Shopify.locale = "en";
        Shopify.currency = {
            "active": "CAD",
            "rate": "1.0"
        };
        Shopify.theme = {
            "name": "Supply — payment icons",
            "id": 37530075192,
            "theme_store_id": 679,
            "role": "main"
        };
        Shopify.theme.handle = "null";
        Shopify.theme.style = {
            "id": null,
            "handle": null
        };
    </script>
    <script type="module">!function(o){(o.Shopify=o.Shopify||{}).modules=!0}(window);</script>
    <script>
        ! function(o) {
            function n() {
                var o = [];

                function n() {
                    o.push(Array.prototype.slice.apply(arguments))
                }
                return n.q = o, n
            }
            var t = o.Shopify = o.Shopify || {};
            t.loadFeatures = n(), t.autoloadFeatures = n()
        }(window);
    </script>
    <script>
        (function() {
            function asyncLoad() {
                var urls = ["\/\/productreviews.shopifycdn.com\/assets\/v4\/spr.js?shop=supply-electronics.myshopify.com"];
                for (var i = 0; i < urls.length; i++) {
                    var s = document.createElement('script');
                    s.type = 'text/javascript';
                    s.async = true;
                    s.src = urls[i];
                    var x = document.getElementsByTagName('script')[0];
                    x.parentNode.insertBefore(s, x);
                }
            };
            if (window.attachEvent) {
                window.attachEvent('onload', asyncLoad);
            } else {
                window.addEventListener('load', asyncLoad, false);
            }
        })();
    </script>
    <script id="__st">
        var __st = {
            "a": 5431637,
            "offset": -14400,
            "reqid": "256fd6ea-e968-4ce2-901e-2e7129dec733",
            "pageurl": "supply-electronics.myshopify.com\/",
            "u": "a29deb35ecc3",
            "p": "home"
        };
    </script>
    <script>
        window.ShopifyPaypalV4VisibilityTracking = true;
    </script>
    <script>
        window['GoogleAnalyticsObject'] = 'ga';
        window['ga'] = window['ga'] || function() {
            (window['ga'].q = window['ga'].q || []).push(arguments);
        };
        window['ga'].l = 1 * new Date();
    </script>
    <script>
        var _gaUTrackerOptions = {
            'allowLinker': true
        };
        ga('create', 'UA-42189134-16', 'auto', _gaUTrackerOptions);
        ga('send', 'pageview');
        (function() {
            ga('require', 'linker');

            function addListener(element, type, callback) {
                if (element.addEventListener) {
                    element.addEventListener(type, callback);
                } else if (element.attachEvent) {
                    element.attachEvent('on' + type, callback);
                }
            }

            function decorate(event) {
                event = event || window.event;
                var target = event.target || event.srcElement;
                if (target && (target.action || target.href)) {
                    ga(function(tracker) {
                        var linkerParam = tracker.get('linkerParam');
                        document.cookie = '_shopify_ga=' + linkerParam + '; ' + 'path=/';
                    });
                }
            }
            addListener(window, 'load', function() {
                for (var i = 0; i < document.forms.length; i++) {
                    if (document.forms[i].action && document.forms[i].action.indexOf('/cart') >= 0) {
                        addListener(document.forms[i], 'submit', decorate);
                    }
                }
                for (var i = 0; i < document.links.length; i++) {
                    if (document.links[i].href && document.links[i].href.indexOf('/checkout') >= 0) {
                        addListener(document.links[i], 'click', decorate);
                    }
                }
            })
        }());
    </script>
    <script>
        window.ShopifyAnalytics = window.ShopifyAnalytics || {};
        window.ShopifyAnalytics.meta = window.ShopifyAnalytics.meta || {};
        window.ShopifyAnalytics.meta.currency = 'CAD';
        var meta = {
            "page": {
                "pageType": "home"
            }
        };
        for (var attr in meta) {
            window.ShopifyAnalytics.meta[attr] = meta[attr];
        }
    </script>
    <script>
        window.ShopifyAnalytics.merchantGoogleAnalytics = function() {

        };
    </script>
    <script class="analytics">
        (function() {
            var customDocumentWrite = function(content) {
                var jquery = null;

                if (window.jQuery) {
                    jquery = window.jQuery;
                } else if (window.Checkout && window.Checkout.$) {
                    jquery = window.Checkout.$;
                }

                if (jquery) {
                    jquery('body').append(content);
                }
            };

            var isDuplicatedThankYouPageView = function() {
                return document.cookie.indexOf('loggedConversion=' + window.location.pathname) !== -1;
            }

            var setCookieIfThankYouPage = function() {
                if (window.location.pathname.indexOf('/checkouts') !== -1 &&
                    window.location.pathname.indexOf('/thank_you') !== -1) {

                    var twoMonthsFromNow = new Date(Date.now());
                    twoMonthsFromNow.setMonth(twoMonthsFromNow.getMonth() + 2);

                    document.cookie = 'loggedConversion=' + window.location.pathname + '; expires=' + twoMonthsFromNow;
                }
            }

            var trekkie = window.ShopifyAnalytics.lib = window.trekkie = window.trekkie || [];
            if (trekkie.integrations) {
                return;
            }
            trekkie.methods = [
                'identify',
                'page',
                'ready',
                'track',
                'trackForm',
                'trackLink'
            ];
            trekkie.factory = function(method) {
                return function() {
                    var args = Array.prototype.slice.call(arguments);
                    args.unshift(method);
                    trekkie.push(args);
                    return trekkie;
                };
            };
            for (var i = 0; i < trekkie.methods.length; i++) {
                var key = trekkie.methods[i];
                trekkie[key] = trekkie.factory(key);
            }
            trekkie.load = function(config) {
                trekkie.config = config;
                var script = document.createElement('script');
                script.type = 'text/javascript';
                script.onerror = function(e) {
                    (new Image()).src = 'http://v.shopify.com/internal_errors/track?error=trekkie_load';
                };
                script.async = true;
                script.src = '../cdn.shopify.com/s/javascripts/tricorder/trekkie.storefront.min7bee.js?v=2020.04.13.1';
                var first = document.getElementsByTagName('script')[0];
                first.parentNode.insertBefore(script, first);
            };
            trekkie.load({
                "Trekkie": {
                    "appName": "storefront",
                    "development": false,
                    "defaultAttributes": {
                        "shopId": 5431637,
                        "isMerchantRequest": null,
                        "themeId": 37530075192,
                        "themeCityHash": "1361009156021012140",
                        "contentLanguage": "en",
                        "currency": "CAD"
                    },
                    "isServerSideCookieWritingEnabled": true
                },
                "Performance": {
                    "navigationTimingApiMeasurementsEnabled": true,
                    "navigationTimingApiMeasurementsSampleRate": 1
                },
                "Session Attribution": {}
            });

            var loaded = false;
            trekkie.ready(function() {
                if (loaded) return;
                loaded = true;

                window.ShopifyAnalytics.lib = window.trekkie;


                var originalDocumentWrite = document.write;
                document.write = customDocumentWrite;
                try {
                    window.ShopifyAnalytics.merchantGoogleAnalytics.call(this);
                } catch (error) {};
                document.write = originalDocumentWrite;
                (function() {
                    if (window.BOOMR && (window.BOOMR.version || window.BOOMR.snippetExecuted)) {
                        return;
                    }
                    window.BOOMR = window.BOOMR || {};
                    window.BOOMR.snippetStart = new Date().getTime();
                    window.BOOMR.snippetExecuted = true;
                    window.BOOMR.snippetVersion = 12;
                    window.BOOMR.application = "core";
                    window.BOOMR.shopId = 5431637;
                    window.BOOMR.themeId = 37530075192;
                    window.BOOMR.url =
                        "../cdn.shopify.com/shopifycloud/boomerang/shopify-boomerang-1.0.0.min.js";
                    var where = document.currentScript || document.getElementsByTagName("script")[0];
                    var parentNode = where.parentNode;
                    var promoted = false;
                    var LOADER_TIMEOUT = 3000;

                    function promote() {
                        if (promoted) {
                            return;
                        }
                        var script = document.createElement("script");
                        script.id = "boomr-scr-as";
                        script.src = window.BOOMR.url;
                        script.async = true;
                        parentNode.appendChild(script);
                        promoted = true;
                    }

                    function iframeLoader(wasFallback) {
                        promoted = true;
                        var dom, bootstrap, iframe, iframeStyle;
                        var doc = document;
                        var win = window;
                        window.BOOMR.snippetMethod = wasFallback ? "if" : "i";
                        bootstrap = function(parent, scriptId) {
                            var script = doc.createElement("script");
                            script.id = scriptId || "boomr-if-as";
                            script.src = window.BOOMR.url;
                            BOOMR_lstart = new Date().getTime();
                            parent = parent || doc.body;
                            parent.appendChild(script);
                        };
                        if (!window.addEventListener && window.attachEvent && navigator.userAgent.match(/MSIE [67]./)) {
                            window.BOOMR.snippetMethod = "s";
                            bootstrap(parentNode, "boomr-async");
                            return;
                        }
                        iframe = document.createElement("IFRAME");
                        iframe.src = "about:blank";
                        iframe.title = "";
                        iframe.role = "presentation";
                        iframe.loading = "eager";
                        iframeStyle = (iframe.frameElement || iframe).style;
                        iframeStyle.width = 0;
                        iframeStyle.height = 0;
                        iframeStyle.border = 0;
                        iframeStyle.display = "none";
                        parentNode.appendChild(iframe);
                        try {
                            win = iframe.contentWindow;
                            doc = win.document.open();
                        } catch (e) {
                            dom = document.domain;
                            iframe.src = "javascript:var d=document.open();d.domain='" + dom + "';void(0);";
                            win = iframe.contentWindow;
                            doc = win.document.open();
                        }
                        if (dom) {
                            doc._boomrl = function() {
                                this.domain = dom;
                                bootstrap();
                            };
                            doc.write("<body onload='document._boomrl();'>");
                        } else {
                            win._boomrl = function() {
                                bootstrap();
                            };
                            if (win.addEventListener) {
                                win.addEventListener("load", win._boomrl, false);
                            } else if (win.attachEvent) {
                                win.attachEvent("onload", win._boomrl);
                            }
                        }
                        doc.close();
                    }
                    var link = document.createElement("link");
                    if (link.relList &&
                        typeof link.relList.supports === "function" &&
                        link.relList.supports("preload") &&
                        ("as" in link)) {
                        window.BOOMR.snippetMethod = "p";
                        link.href = window.BOOMR.url;
                        link.rel = "preload";
                        link.as = "script";
                        link.addEventListener("load", promote);
                        link.addEventListener("error", function() {
                            iframeLoader(true);
                        });
                        setTimeout(function() {
                            if (!promoted) {
                                iframeLoader(true);
                            }
                        }, LOADER_TIMEOUT);
                        BOOMR_lstart = new Date().getTime();
                        parentNode.appendChild(link);
                    } else {
                        iframeLoader(false);
                    }

                    function boomerangSaveLoadTime(e) {
                        window.BOOMR_onload = (e && e.timeStamp) || new Date().getTime();
                    }
                    if (window.addEventListener) {
                        window.addEventListener("load", boomerangSaveLoadTime, false);
                    } else if (window.attachEvent) {
                        window.attachEvent("onload", boomerangSaveLoadTime);
                    }
                    if (document.addEventListener) {
                        document.addEventListener("onBoomerangLoaded", function(e) {
                            e.detail.BOOMR.init({
                                ResourceTiming: {
                                    enabled: true,
                                    trackedResourceTypes: ["script", "img", "css"]
                                },
                            });
                            e.detail.BOOMR.t_end = new Date().getTime();
                        });
                    } else if (document.attachEvent) {
                        document.attachEvent("onpropertychange", function(e) {
                            if (!e) e = event;
                            if (e.propertyName === "onBoomerangLoaded") {
                                e.detail.BOOMR.init({
                                    ResourceTiming: {
                                        enabled: true,
                                        trackedResourceTypes: ["script", "img", "css"]
                                    },
                                });
                                e.detail.BOOMR.t_end = new Date().getTime();
                            }
                        });
                    }
                })();


                if (!isDuplicatedThankYouPageView()) {
                    setCookieIfThankYouPage();

                    window.ShopifyAnalytics.lib.page(
                        null, {
                            "pageType": "home"
                        }
                    );


                }
            });


            var eventsListenerScript = document.createElement('script');
            eventsListenerScript.async = true;
            eventsListenerScript.src = "../cdn.shopify.com/s/assets/shop_events_listener-2c6237918c4bbec8783d8ceecd5759edc38afa9b5bef55134462710955517539.js";
            document.getElementsByTagName('head')[0].appendChild(eventsListenerScript);

        })();
    </script>
    <script integrity="sha256-WJ/zNC1jntI8lPX8EeA9ZOB4jipKaHOR6+7u8g6vL1A=" crossorigin="anonymous" data-source-attribution="shopify.loadfeatures" defer="defer" src="browser/customer/assets/storefront/load_feature-589ff3342d639ed23c94f5fc11e03d64e0788e2a4a687391ebeeeef20eaf2f50.js"></script>
    <script integrity="sha256-EYppj7RbseKnaugbP4EJXR4sMs7TPdTpPmQ3i163eNA=" data-source-attribution="shopify.dynamic-checkout" defer="defer" src="browser/customer/assets/storefront/features-118a698fb45bb1e2a76ae81b3f81095d1e2c32ced33dd4e93e64378b5eb778d0.js" crossorigin="anonymous"></script>
    <script async="async" src="browser/customer/www.google-analytics.com/analytics.js"></script>
    <script defer="defer" src="browser/customer/assets/themes_support/ga_urchin_forms-99e991855b3d8ddc69e625c68ab0579dd9927b611c2ec4943d396c72e3af0849.js"></script>


    <script>
        window.performance && window.performance.mark && window.performance.mark('shopify.content_for_header.end');
    </script>



    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <!--[if (lte IE 9) ]>
    <script src="browser/customerfiles/1/0543/1637/t/16/assets/match-media.min.js?6" type="text/javascript"></script><![endif]-->





    <script src="browser/customer/files/1/0543/1637/t/16/assets/jquery-2.2.3.min4dfb.js" type="text/javascript"></script>

    <!--[if (gt IE 9)|!(IE)]><!-->
    <script src="browser/customer/files/1/0543/1637/t/16/assets/lazysizes.minb2e8.js" async="async"></script>
    <!--<![endif]-->
    <!--[if lte IE 9]><script src="browser/customer/files/1/0543/1637/t/16/assets/lazysizes.min.js"></script><![endif]-->

    <!--[if (gt IE 9)|!(IE)]><!-->
    <script src="browser/customer/files/1/0543/1637/t/16/assets/vendor5ffc.js" defer="defer"></script>
    <!--<![endif]-->
    <!--[if lte IE 9]><script src="browser/customer/files/1/0543/1637/t/16/assets/vendor.js"></script><![endif]-->

    <!--[if (gt IE 9)|!(IE)]><!-->
    <script src="browser/customer/files/1/0543/1637/t/16/assets/theme4d8f.js" defer="defer"></script>
    <!--<![endif]-->
    <!--[if lte IE 9]><script src="browser/customer/files/1/0543/1637/t/16/assets/theme.js"></script><![endif]-->


</head>