<div id="shopify-section-header" class="shopify-section header-section">
    <header class="site-header" role="banner" data-section-id="header" data-section-type="header-section">
        <div class="wrapper">

            <div class="grid--full">
                <div class="grid-item large--one-half">

                    <h1 class="header-logo" itemscope itemtype="">




                        <a href="index.html" itemprop="url">
                            <div class="lazyload__image-wrapper no-js header-logo__image" style="max-width:100px;">
                                <div style="padding-top:28.265524625267663%;">
                                   <img class="lazyload js" data-src="browser/customer/images/log.png"
                                        data-widths="[180, 360, 540, 720, 900, 1080, 1296, 1512, 1728, 2048]"
                                        data-aspectratio="3.537878787878788"
                                        data-sizes="auto" alt="Digitalshop" style="width:100px;">

                                </div>
                            </div>

                        </a>


                    </h1>

                </div>

                <div class="grid-item large--one-half text-center large--text-right">

                    <div class="site-header--text-links">



                        <span class="site-header--meta-links medium-down--hide">

                            <a href="login" id="customer_login_link">Sign in</a>
                            <span class="site-header--spacer">or</span>
                            <a href="register" id="customer_register_link">Create an Account</a>

                        </span>

                    </div>

                    <br class="medium-down--hide">


                    <form action="" method="get" class="search-bar" role="search">
                        <input type="hidden" name="type" value="product">

                        <input type="search" name="q" value="" placeholder="Search all products..." aria-label="Search all products...">
                        <button type="submit" class="search-bar--submit icon-fallback-text">
                            <span class="fas fa-search"></span>
                            <span class="fallback-text">Search</span>
                        </button>
                    </form>


                    <a href="cart" class="header-cart-btn cart-toggle">
                        <span class="fas fa-shopping-cart"></span>
                        Cart <span class="cart-count cart-badge--desktop hidden-count">0</span>
                    </a>
                </div>
            </div>

        </div>
    </header>

    <div id="mobileNavBar">
        <div class="display-table-cell">
            <button class="menu-toggle mobileNavBar-link" aria-controls="navBar" aria-expanded="false"><span class="icon icon-hamburger" aria-hidden="true"></span>Menu</button>
        </div>
        <div class="display-table-cell">
            <a href="cart" class="cart-toggle mobileNavBar-link">
                <span class="fas fa-shopping-cart"></span>
                Cart <span class="cart-count hidden-count">0</span>
            </a>
        </div>
    </div>

    <nav class="nav-bar" id="navBar" role="navigation">
        <div class="wrapper">
            <form action="" method="get" class="search-bar" role="search">
                <input type="hidden" name="type" value="product">

                <input type="search" name="q" value="" placeholder="Search all products..." aria-label="Search all products...">
                <button type="submit" class="search-bar--submit icon-fallback-text">
                    <span class="fas fa-search" ></span>
                    <span class="fallback-text">Search</span>
                </button>
            </form>

            <ul class="mobile-nav" id="MobileNav">

                <li class="large--hide">
                    <a href="index">Home</a>
                </li>




                <li class="mobile-nav--has-dropdown " aria-haspopup="true">
                    <a href="collectionList" class="mobile-nav--link" data-meganav-type="parent">
                        Collections
                    </a>
                    <button class="fas fa-arrow-down  mobile-nav--button" aria-expanded="false" aria-label="">
                    </button>
                    <ul id="MenuParent-1" class="mobile-nav--dropdown " data-meganav-dropdown>


                        <li>
                            <a href="collection" class="mobile-nav--link" data-meganav-type="child">
                                Nokia
                            </a>
                        </li>



                        <li>
                            <a href="collection" class="mobile-nav--link" data-meganav-type="child">
                                Infinix
                            </a>
                        </li>



                        <li>
                            <a href="collection" class="mobile-nav--link" data-meganav-type="child">
                                Itel
                            </a>
                        </li>



                        <li>
                            <a href="collections/analog-cameras.html" class="mobile-nav--link" data-meganav-type="child">
                                Analog
                            </a>
                        </li>



                        <li>
                            <a href="collections/leica-q.html" class="mobile-nav--link" data-meganav-type="child">
                                Leica Q
                            </a>
                        </li>



                        <li>
                            <a href="collections/leica-sofort.html" class="mobile-nav--link" data-meganav-type="child">
                                Leica Sofort System
                            </a>
                        </li>



                        <li>
                            <a href="collections/compact.html" class="mobile-nav--link" data-meganav-type="child">
                                Compact
                            </a>
                        </li>



                        <li>
                            <a href="collections/leica-t.html" class="mobile-nav--link" data-meganav-type="child">
                                Leica T
                            </a>
                        </li>



                        <li>
                            <a href="collections/leica-x.html" class="mobile-nav--link" data-meganav-type="child">
                                Leica X
                            </a>
                        </li>


                    </ul>
                </li>




                <li class=" " aria-haspopup="">
                    <a href="about" class="mobile-nav--link" data-meganav-type="child">
                        About Us
                    </a>
                   
                </li>



                <li>
                    <a href="contact" class="mobile-nav--link" data-meganav-type="child">
                        Contact Us
                    </a>
                </li>



                <li>
                    <a href="faq" class="mobile-nav--link" data-meganav-type="child">
                        FAQ
                    </a>
                </li>



                <li>
                    <a href="news" class="mobile-nav--link" data-meganav-type="child">
                        News/Job
                    </a>
                </li>



                <li>
                    <a href="" class="mobile-nav--link" data-meganav-type="child">
                        Product Tracking
                    </a>
                </li>





                <li class="customer-navlink large--hide"><a href="login" id="customer_login_link">Sign in</a></li>
                <li class="customer-navlink large--hide"><a href="register" id="customer_register_link">Create an Account</a></li>


            </ul>

            <ul class="site-nav" id="AccessibleNav">

                <li class="">
                    <a href="index">Home</a>
                </li>




                <li class="site-nav--has-dropdown " aria-haspopup="true">
                    <a href="collectionList" class="site-nav--link" data-meganav-type="parent" aria-controls="MenuParent-1" aria-expanded="false">
                        Collection
                        <span class="fas fa-arrow-down"></span>
                    </a>
                    <ul id="MenuParent-1" class="site-nav--dropdown " data-meganav-dropdown>


                        <li>
                            <a href="collection" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                                Nokia
                            </a>
                        </li>



                        <li>
                            <a href="collection" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                                Tecon
                            </a>
                        </li>



                        <li>
                            <a href="collection" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                                Samsung
                            </a>
                        </li>



                        <li>
                            <a href="collection" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                                Apple
                            </a>
                        </li>



                        <li>
                            <a href="collection" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                                Itel
                            </a>
                        </li>



                        <li>
                            <a href="collection" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                               Gionee
                            </a>
                        </li>



                        <li>
                            <a href="collection" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                                Infinix
                            </a>
                        </li>



                        <li>
                            <a href="collections/leica-t.html" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                                Leica T
                            </a>
                        </li>



                        <li>
                            <a href="collections/leica-x.html" class="site-nav--link" data-meganav-type="child" tabindex="-1">
                                Leica X
                            </a>
                        </li>


                    </ul>
                </li>

                <li>
                    <a href="about" class="site-nav--link" data-meganav-type="child">
                        About Us
                    </a>
                </li>


            
                <li>
                    <a href="contact" class="site-nav--link" data-meganav-type="child">
                        Contact Us
                    </a>
                </li>



                <li>
                    <a href="faq" class="site-nav--link" data-meganav-type="child">
                        FAQ
                    </a>
                </li>



                <li>
                    <a href="news" class="site-nav--link" data-meganav-type="child">
                        News/Job
                    </a>
                </li>



                <li>
                    <a href="" class="site-nav--link" data-meganav-type="child">
                        Product Tracking
                    </a>
                </li>





                <li class="customer-navlink large--hide"><a href="login" id="customer_login_link">Sign in</a></li>
                <li class="customer-navlink large--hide"><a href="register" id="customer_register_link">Create an Account</a></li>


            </ul>
        </div>
    </nav>




</div>