<?php
use model\Links;
?>
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu" app-navigation>
        <div class="pcoded-navigatio-lavel">Navigation</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="active pcoded-trigger">
                <a href="#" app-link="<?=Links::adm_dashboard?>">
                    <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                    <span class="pcoded-mtext">Dashboard</span>
                </a>
            </li>
            <li class="">
                <a href="#" app-link="<?=Links::adm_order?>">
                    <span class="pcoded-micon"><i class="feather icon-menu"></i></span>
                    <span class="pcoded-mtext">Orders</span>
                </a>
            </li>
            <li class="">
                <a href="#" app-link="<?=Links::adm_customer_list?>">
                    <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                    <span class="pcoded-mtext">Customers</span>

                </a>
            </li>
            <li class="">
                <a href="javascript:" app-link="<?=Links::adm_brands?>">
                    <span class="pcoded-micon"><i class="feather icon-box"></i></span>
                    <span class="pcoded-mtext">Products</span>
                </a>
            </li>
            <li class="">
                <a href="#" app-link="<?=Links::adm_tickets?>">
                    <span class="pcoded-micon"><i class="feather icon-layers"></i></span>
                    <span class="pcoded-mtext">Tickets</span>
                </a>
            </li>
            <li class="pcoded-hasmenu">
                <a href="javascript:">
                    <span class="pcoded-micon"><i class="feather icon-layers"></i></span>
                    <span class="pcoded-mtext">Staff</span>
                </a>
                <ul class="pcoded-submenu">
                    <li>
                        <a href="#" app-link="<?=Links::adm_staff_add?>">
                            <span class="pcoded-mtext">Add Staff</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_staff_list?>">
                            <span class="pcoded-mtext">List Staffs</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="pcoded-hasmenu">
                <a href="javascript:">
                    <span class="pcoded-micon"><i class="feather icon-settings"></i></span>
                    <span class="pcoded-mtext">Settings</span>
                </a>
                <ul class="pcoded-submenu">
                    <li class="">
                        <a href="#" app-link="<?=Links::adm_brand_add?>">
                            <span class="pcoded-mtext">Add Brand</span>
                        </a>
                    </li>

                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_brand_list?>">
                            <span class="pcoded-mtext">Manage Brand</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_model_add?>">
                            <span class="pcoded-mtext">Add Models</span>
                        </a>
                    </li>

                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_model_list?>">
                            <span class="pcoded-mtext">Manage Models</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="#" app-link="<?=Links::adm_password?>">
                            <span class="pcoded-mtext">Passwords</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <div class="pcoded-navigatio-lavel">Jobs</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="pcoded-hasmenu">
                <a href="javascript:">
                    <span class="pcoded-micon"><i class="feather icon-box"></i></span>
                    <span class="pcoded-mtext">Jobs</span>
                </a>
                <ul class="pcoded-submenu">
                    <li>
                        <a href="#" app-link="<?=Links::adm_jobs_add?>">
                            <span class="pcoded-mtext">Add Jobs</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" app-link="<?=Links::adm_jobs_list?>">
                            <span class="pcoded-mtext">Posted Jobs</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>
