<?php

use application\locations\Url; ?>
<head>
    <title>Tele-Tech Admin </title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="#">
    <meta name="keywords" content="Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
    <meta name="author" content="#">

    <base href="<?=Url::Url();?>/">

    <link rel="icon" href="" type="image/x-icon">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="browser/dash/vendor/bootstrap/css/bootstrap.min.css">


    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.css" type="text/css">
    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.brighttheme.css" type="text/css">
    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.buttons.css" type="text/css">
    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.history.css" type="text/css">
    <link rel="stylesheet" href="browser/dash/vendor/pnotify/css/pnotify.mobile.css" type="text/css">


    <link rel="stylesheet" href="browser/dash/vendor/sweetalert/css/sweetalert.css" type="text/css">




    <link rel="stylesheet" type="text/css" href="browser/dash/icons/feather/css/feather.css">
    <link rel="stylesheet" type="text/css" href="browser/dash/icons/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="browser/dash/css/jquery.mCustomScrollbar.css">
    <link rel="stylesheet" type="text/css" href="browser/dash/css/style.css">
    <link rel="stylesheet" type="text/css" href="browser/dash/css/custom.css">
</head>