
<head>
    <title>Admin Dashboard </title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="#">
    <meta name="keywords" content=" Mobile, iOS, Android, apple">
    <meta name="author" content="#">

    <link rel="icon" href="browser/adminty/assets/images/favicon.ico" type="image/x-icon">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="browser/adminty/bower_components/bootstrap/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="browser/adminty/assets/icon/feather/css/feather.css">

    <link rel="stylesheet" type="text/css" href="browser/adminty/assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="browser/adminty/assets/css/jquery.mCustomScrollbar.css">
</head>
