
<script data-cfasync="false" src="../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/bower_components/jquery/js/jquery.min.js"></script>
<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/bower_components/jquery-ui/js/jquery-ui.min.js"></script>
<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/bower_components/popper.js/js/popper.min.js"></script>
<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/bower_components/bootstrap/js/bootstrap.min.js"></script>

<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/bower_components/jquery-slimscroll/js/jquery.slimscroll.js"></script>

<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/bower_components/modernizr/js/modernizr.js"></script>

<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/bower_components/chart.js/js/Chart.js"></script>

<script src="browser/adminty/assets/pages/widget/amchart/amcharts.js" type="1c43df19d905d4e2fd7b3af6-text/javascript"></script>
<script src="browser/adminty/assets/pages/widget/amchart/serial.js" type="1c43df19d905d4e2fd7b3af6-text/javascript"></script>
<script src="browser/adminty/assets/pages/widget/amchart/light.js" type="1c43df19d905d4e2fd7b3af6-text/javascript"></script>
<script src="browser/adminty/assets/js/jquery.mCustomScrollbar.concat.min.js" type="1c43df19d905d4e2fd7b3af6-text/javascript"></script>
<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="../files/assets/js/SmoothScroll.js"></script>
<script src="browser/adminty/assets/js/pcoded.min.js" type="1c43df19d905d4e2fd7b3af6-text/javascript"></script>

<script src="browser/adminty/assets/js/vartical-layout.min.js" type="1c43df19d905d4e2fd7b3af6-text/javascript"></script>
<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/assets/pages/dashboard/custom-dashboard.js"></script>
<script type="1c43df19d905d4e2fd7b3af6-text/javascript" src="browser/adminty/assets/js/script.min.js"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="1c43df19d905d4e2fd7b3af6-text/javascript"></script>
<script type="1c43df19d905d4e2fd7b3af6-text/javascript">
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
<script src="browser/adminty/ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="1c43df19d905d4e2fd7b3af6-|49" defer=""></script>
</body>

<!-- Mirrored from colorlib.com//polygon/adminty/default/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 28 Apr 2020 10:58:59 GMT -->

</html>